"""empty message

Revision ID: 03e35609de61
Revises: 490a89e031c0
Create Date: 2018-04-19 15:39:27.783530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e35609de61'
down_revision = '490a89e031c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clue_groups', sa.Column('name', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clue_groups', 'name')
    # ### end Alembic commands ###
