"""empty message

Revision ID: 490a89e031c0
Revises: a77d5e84852f
Create Date: 2018-03-29 10:35:50.091895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490a89e031c0'
down_revision = 'a77d5e84852f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('clue_group_id', sa.String(length=36), nullable=True),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clue_group_id'], ['clue_groups.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clues')
    # ### end Alembic commands ###
