"""empty message

Revision ID: 49e93ed839b0
Revises: 47a43f2671d4
Create Date: 2018-03-02 10:54:29.729091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e93ed839b0'
down_revision = '47a43f2671d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('payments', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'updated_on')
    op.drop_column('payments', 'created_on')
    # ### end Alembic commands ###
