"""empty message

Revision ID: 89945cb7e50d
Revises: ffd52c9d6bda
Create Date: 2018-02-26 16:12:14.700839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89945cb7e50d'
down_revision = 'ffd52c9d6bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('firstname', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=64), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'phone')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'enabled')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
