"""empty message

Revision ID: abc92150a3aa
Revises: a3294373334d
Create Date: 2018-03-07 15:28:01.070358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc92150a3aa'
down_revision = 'a3294373334d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_users', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('course_users', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('courses', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('courses', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('schools', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('schools', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_roles', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_roles', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_on')
    op.drop_column('users', 'created_on')
    op.drop_column('user_roles', 'updated_on')
    op.drop_column('user_roles', 'created_on')
    op.drop_column('schools', 'updated_on')
    op.drop_column('schools', 'created_on')
    op.drop_column('courses', 'updated_on')
    op.drop_column('courses', 'created_on')
    op.drop_column('course_users', 'updated_on')
    op.drop_column('course_users', 'created_on')
    # ### end Alembic commands ###
