"""empty message

Revision ID: f501955cb902
Revises: 386ec228abb8
Create Date: 2018-01-31 12:58:51.798964

"""
from alembic import op
import sqlalchemy as sa
import uuid

# revision identifiers, used by Alembic.
revision = 'f501955cb902'
down_revision = '386ec228abb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    role_tabe = op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('schools', 'id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_server_default=sa.text("nextval('schools_id_seq'::regclass)"))
    op.alter_column('students', 'id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_server_default=sa.text("nextval('students_id_seq'::regclass)"))
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))


    op.bulk_insert(role_tabe, [
        {'id': str(uuid.uuid4()), 'name': 'admin', 'description': 'admin of each school'},
        {'id': str(uuid.uuid4()), 'name': 'staff', 'description': 'staff of each school'},
        {'id': str(uuid.uuid4()), 'name': 'student', 'description': 'student'}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=32),
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('students', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=32),
               existing_server_default=sa.text("nextval('students_id_seq'::regclass)"))
    op.alter_column('schools', 'id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=32),
               existing_server_default=sa.text("nextval('schools_id_seq'::regclass)"))
    op.drop_table('roles')
    # ### end Alembic commands ###
